### ISSUE TITLE
Toggle Emission values of Light Fixtures When Lights Active

### ISSUE THREAD

**Issue by KailaniPinon** [VRR-Production/TidyTrainers#29]
**Is your feature request related to a problem? Please describe.**
Room seems a bit odd when lights are on, but the light fixtures remain unchanged. I think functionality that alters the emission textures can improve the world experience. Some of the lights have emission textures, but altering those textures have not been developed on the programming team.

**Describe the solution you'd like**
When the lights are on, the emission value changes so that it appears brighter and on. When the lights are off, the emission value changes so that it appears darker and off.

**Describe alternatives you've considered**
[none]

**Additional context**
Not a high priority, but it would help with the environment experience

**Comment by VRR-Production** [comment]
@CoalontheFire next week in class, please see if you can implement a "lit" emissive map to all lights and key they to flicking specific light switches
